import json
import pymysql
import os

def generate():
    print("Generating vendor_spells.lua...")
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(BASE_DIR, "config.json"), "r") as f:
        config = json.load(f)
        
    db = pymysql.connect(
        host=config["host"],
        port=config["port"],
        user=config["user"],
        password=config["password"],
        database=config["database"],
        cursorclass=pymysql.cursors.DictCursor
    )
    
    try:
        with db.cursor() as cursor:
            # Get all vendor available spell IDs
            cursor.execute("""
                SELECT DISTINCT i.scrolleffect 
                FROM items i 
                JOIN merchantlist m ON i.id = m.item 
                WHERE i.scrolleffect > 0
            """)
            vendor_spell_ids = {row['scrolleffect'] for row in cursor.fetchall()}
            
            # Now, for each class (1 to 16), we want a list of available spells by level.
            # The spells_new table contains classes1 to classes16 columns
            cursor.execute("SELECT id, name, IsDiscipline, classes1, classes2, classes3, classes4, classes5, classes6, classes7, classes8, classes9, classes10, classes11, classes12, classes13, classes14, classes15, classes16 FROM spells_new")
            all_spells = cursor.fetchall()
            
            # Structure: class_spells[class_id][level] = [spell_id, spell_id, ...]
            class_spells = {c: {} for c in range(1, 17)}
            
            for spell in all_spells:
                spell_id = spell['id']
                if spell_id not in vendor_spell_ids:
                    continue
                if spell['IsDiscipline'] != 0:
                    continue
                
                # Check each class column
                for c in range(1, 17):
                    level_req = spell[f'classes{c}']
                    if level_req < 255: # 255 means the class cannot use it
                        if level_req not in class_spells[c]:
                            class_spells[c][level_req] = []
                        class_spells[c][level_req].append(spell_id)
            
            # Generate the Lua table
            out_path = os.path.join(BASE_DIR, "MacroQuestRof2", "lua", "vendor_spells.lua")
            with open(out_path, "w") as f:
                f.write("-- GENERATED BY generate_vendor_spells.py\n")
                f.write("-- DO NOT EDIT MANUALLY\n\n")
                f.write("local vendor_spells = {\n")
                
                for c in range(1, 17):
                    f.write(f"    [{c}] = {{\n")
                    levels = sorted(class_spells[c].keys())
                    for lvl in levels:
                        spells_str = ", ".join(str(s) for s in class_spells[c][lvl])
                        f.write(f"        [{lvl}] = {{ {spells_str} }},\n")
                    f.write("    },\n")
                    
                f.write("}\n\n")
                f.write("return vendor_spells\n")
                
            print(f"Successfully generated {out_path} with {len(vendor_spell_ids)} vendor spells mapped by class and level!")
            
    except Exception as e:
        print("Error:", e)
    finally:
        db.close()

if __name__ == "__main__":
    generate()
